// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("BeltsRaw")]
public partial class BeltsRaw
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateLogged { get; set; }

    public int ShaftId { get; set; }

    public int ShiftId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? WetTonnes { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string SampleId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TCu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TCo { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Moisture { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Cu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Co { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EnteredOn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EnteredBy { get; set; }

    [ForeignKey("ShaftId")]
    [InverseProperty("BeltsRaws")]
    public virtual Shift Shaft { get; set; }

    [ForeignKey("ShaftId")]
    [InverseProperty("BeltsRaws")]
    public virtual Shaft ShaftNavigation { get; set; }
}