// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("Bin")]
public partial class Bin
{
    [Key]
    public int StockPId { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("StockP")]
    public virtual ICollection<StockPile> StockPiles { get; set; } = new List<StockPile>();
}