// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("Level")]
public partial class Level
{
    [Key]
    public int LevelId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LevelDescription { get; set; }

    public int ShaftId { get; set; }

    [ForeignKey("ShaftId")]
    [InverseProperty("Levels")]
    public virtual Shaft Shaft { get; set; }

    [InverseProperty("Level")]
    public virtual ICollection<StopeDefinition> StopeDefinitions { get; set; } = new List<StopeDefinition>();

    [InverseProperty("Level")]
    public virtual ICollection<UGSurvey> UGSurveys { get; set; } = new List<UGSurvey>();
}