// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("Measure")]
public partial class Measure
{
    public int Id { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string MeasureCode { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string MeasureDescription { get; set; }
}