// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("MineModel")]
public partial class MineModel
{
    [Key]
    public int ModelId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ModelDescription { get; set; }

    [InverseProperty("MineModel")]
    public virtual ICollection<StopeDefinition> StopeDefinitions { get; set; } = new List<StopeDefinition>();

    [InverseProperty("Model")]
    public virtual ICollection<UGSurvey> UGSurveys { get; set; } = new List<UGSurvey>();
}