// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("RMD")]
public partial class RMD
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateTo { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Tonnes { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Cu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Co { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TCu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TCo { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string Comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EnteredOn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EnteredBy { get; set; }
}