// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("Shaft")]
public partial class Shaft
{
    [Key]
    public int ShaftId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ShaftName { get; set; }

    [InverseProperty("ShaftNavigation")]
    public virtual ICollection<BeltsRaw> BeltsRaws { get; set; } = new List<BeltsRaw>();

    [InverseProperty("Shaft")]
    public virtual ICollection<StopeDevelopment> StopeDevelopments { get; set; } = new List<StopeDevelopment>();

    [InverseProperty("Shaft")]
    public virtual ICollection<UGStopeDetail> UGStopeDetails { get; set; } = new List<UGStopeDetail>();

    [InverseProperty("Shaft")]
    public virtual ICollection<UGStopesRaw> UGStopesRaws { get; set; } = new List<UGStopesRaw>();

    [InverseProperty("Shaft")]
    public virtual ICollection<UGSurvey> UGSurveys { get; set; } = new List<UGSurvey>();
}