// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

public partial class StockPile
{
    [Key]
    public int Id { get; set; }

    public int StockPId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OpeningTonnes { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ClosingTonnes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateTo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EnteredBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EnteredOn { get; set; }

    [ForeignKey("StockPId")]
    [InverseProperty("StockPiles")]
    public virtual Bin StockP { get; set; }
}