// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Reconcilor.Domain.Models;

[Table("UGStopeDetail")]
public partial class UGStopeDetail
{
    [Key]
    public int Id { get; set; }

    public int StopeDefId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateEntered { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Tonnes { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TCu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TCo { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Cu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Co { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EnteredBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EnteredOn { get; set; }

    [ForeignKey("StopeDefId")]
    [InverseProperty("UGStopeDetails")]
    public virtual StopeDefinition StopeDef { get; set; }
}